<?xml version="1.0" encoding="utf-8"?><Database Name="Hub" Class="DataHubDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=95.84.164.113;Initial Catalog=Hub;Persist Security Info=True;User ID=hubber" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HubConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Comm_Read" Method="Comm_Read">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Comm_ReadResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ownerHubID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="subjectCommID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="areaCommID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="adminCommID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.OwnerHub_Read" Method="OwnerHub_Read">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="OwnerHub_ReadResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="linkFB" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SubjectComm_Del" Method="SubjectComm_Del">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SubjectComm_ReadDict" Method="SubjectComm_ReadDict">
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SubjectComm_ReadDictResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ownerHubID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ErrorLog_Save" Method="ErrorLog_Save">
    <Parameter Name="Session" Parameter="session" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="FuncName" Parameter="funcName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Params" Parameter="params" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ErrorText" Parameter="errorText" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="ErrorLog_SaveResult">
      <Column Name="" Member="Column1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdminComm_ReadDict" Method="AdminComm_ReadDict">
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="AdminComm_ReadDictResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="linkFB" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SessionReq_Save" Method="SessionReq_Save">
    <Parameter Name="dID" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(64)" />
    <ElementType Name="SessionReq_SaveResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ownerHubID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SubjectComm_Save" Method="SubjectComm_Save">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(256)" />
    <ElementType Name="SubjectComm_SaveResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdminComm_Del" Method="AdminComm_Del">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdminComm_Save" Method="AdminComm_Save">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="linkFB" Type="System.String" DbType="VarChar(512)" />
    <ElementType Name="AdminComm_SaveResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ownerHubId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="linkFB" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetOwnerHubID" Method="GetOwnerHubID">
    <Parameter Name="sessionID" Type="System.String" DbType="VarChar(36)" />
    <ElementType Name="GetOwnerHubIDResult">
      <Column Name="ownerHubID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Comm_Del" Method="Comm_Del">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comm_ReadDict" Method="Comm_ReadDict">
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Comm_ReadDictResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="photoLink" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="ownerHubID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ownerHubID_firstName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="ownerHubID_lastName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="ownerHubID_linkFB" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="subjectCommID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="subjectCommID_name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="areaCommID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaCommID_name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="adminCommID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="adminCommID_firstName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="adminCommID_lastName" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="adminCommID_phone" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="adminCommID_linkFB" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="groupID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.StaCommVKDaily_Save" Method="StaCommVKDaily_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="dayDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="commViews" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commVisitors" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReach" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReachSubscribers" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commSubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commUnsubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commLikes" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commComments" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReposts" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commPostCount" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commMembers" Type="System.Int32" DbType="Int" />
    <Parameter Name="commPhotoLink" Type="System.String" DbType="VarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.OwnerHub_Save" Method="OwnerHub_Save">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="linkFB" Type="System.String" DbType="VarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Owner_Set" Method="Owner_Set">
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="sessionReqID" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Session_Save" Method="Session_Save">
    <Parameter Name="sessionReqID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="dID" Type="System.String" DbType="VarChar(64)" />
    <ElementType Name="Session_SaveResult">
      <Column Name="sessionID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ownerHubID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="isNewMember" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.StaCommVKDaily_Report" Method="StaCommVKDaily_Report">
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="isPast" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="StaCommVKDaily_ReportResult">
      <Column Name="comm_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="comm_name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="comm_photoLink" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="comm_photoLinkBig" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="comm_groupID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="subjectComm_name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="areaComm_code" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="adminComm_fullName" Type="System.String" DbType="VarChar(1025) NOT NULL" CanBeNull="false" />
      <Column Name="adminComm_linkFB" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="lastRequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="increaseNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="increaseDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subscribed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subscribedNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="subscribedOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="subscribedDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subscribedDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unsubscribed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="visitors" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="visitorsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="visitorsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="visitorsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="visitorsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="views" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="viewsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="viewsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="viewsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="viewsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reachSubscribers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="postCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="postCountNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="postCountOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="postCountDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="postCountDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="members" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersNew" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersOld" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="likes" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="likesNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="likesOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="likesDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="likesDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comments" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commentsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commentsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commentsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commentsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reposts" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="repostsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="repostsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="repostsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="repostsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.StaCommVKWeekly_Report" Method="StaCommVKWeekly_Report">
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="StaCommVKWeekly_ReportResult">
      <Column Name="comm_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="comm_name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="comm_photoLink" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="comm_photoLinkBig" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="comm_groupID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="subjectComm_name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="areaComm_code" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="adminComm_fullName" Type="System.String" DbType="VarChar(1025) NOT NULL" CanBeNull="false" />
      <Column Name="adminComm_linkFB" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="lastRequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="increaseNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="increaseDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subscribed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subscribedNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="subscribedOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="subscribedDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subscribedDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unsubscribed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unsubscribedDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="visitors" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="visitorsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="visitorsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="visitorsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="visitorsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="views" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="viewsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="viewsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="viewsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="viewsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reachSubscribers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reachSubscribersDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="postCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="postCountNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="postCountOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="postCountDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="postCountDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="members" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersNew" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersOld" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="membersDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="likes" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="likesNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="likesOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="likesDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="likesDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comments" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commentsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commentsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commentsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commentsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reposts" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="repostsNew" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="repostsOld" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="repostsDif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="repostsDifPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Comm_Save" Method="Comm_Save">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="subjectCommID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="adminCommID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="link" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="areaCommID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StaCommVKGraph_Report" Method="StaCommVKGraph_Report">
    <Parameter Name="ownerHubID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="StaCommVKGraph_ReportResult">
      <Column Name="commLikes" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commComments" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commShare" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commRemoved" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commMembers" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="commMembersLost" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="dayDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="isLast" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isFuture" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cntReq" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>