<?xml version="1.0" encoding="utf-8"?><Database Name="Threads" Class="DataThreadsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=95.84.164.113;Initial Catalog=Threads;Persist Security Info=True;User ID=member" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ThreadsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ColumnCommunity" Member="ColumnCommunity">
    <Type Name="ColumnCommunity">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CommunityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteNote" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="ColumnCommunity_Entry" Member="Entry" ThisKey="ID" OtherKey="ColumnID" Type="Entry" />
      <Association Name="Community_ColumnCommunity" Member="Community" ThisKey="CommunityID" OtherKey="ID" Type="Community" IsForeignKey="true" />
      <Association Name="Person_ColumnCommunity" Member="Person" ThisKey="CreatorID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Community" Member="Community">
    <Type Name="Community">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="LogoLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Decription" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClosedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClosedNote" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Association Name="Community_ColumnCommunity" Member="ColumnCommunity" ThisKey="ID" OtherKey="CommunityID" Type="ColumnCommunity" />
      <Association Name="Community_Entry" Member="Entry" ThisKey="ID" OtherKey="CommunityID" Type="Entry" />
      <Association Name="Person_Community" Member="Person" ThisKey="OwnerID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Person">
    <Type Name="Person">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="PhotoLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="About" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="JoinedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LeaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LeaveNote" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Association Name="Person_ColumnCommunity" Member="ColumnCommunity" ThisKey="ID" OtherKey="CreatorID" Type="ColumnCommunity" />
      <Association Name="Person_Community" Member="Community" ThisKey="ID" OtherKey="OwnerID" Type="Community" />
      <Association Name="Person_Entry" Member="Entry" ThisKey="ID" OtherKey="CreatorID" Type="Entry" />
    </Type>
  </Table>
  <Table Name="dbo.Entry" Member="Entry">
    <Type Name="Entry">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CommunityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ColumnID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EntryText" Type="System.String" DbType="VarChar(4048)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteNote" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Association Name="ColumnCommunity_Entry" Member="ColumnCommunity" ThisKey="ColumnID" OtherKey="ID" Type="ColumnCommunity" IsForeignKey="true" />
      <Association Name="Community_Entry" Member="Community" ThisKey="CommunityID" OtherKey="ID" Type="Community" IsForeignKey="true" />
      <Association Name="Person_Entry" Member="Person" ThisKey="CreatorID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.[Entry.Save]" Method="Entry_Save">
    <Parameter Name="CommunityID" Parameter="communityID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ColumnID" Parameter="columnID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="CreatorID" Parameter="creatorID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="EntryText" Parameter="entryText" Type="System.String" DbType="VarChar(4048)" />
    <ElementType Name="Entry_SaveResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Country.ReadDict]" Method="Country_ReadDict">
    <ElementType Name="Country_ReadDictResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[SessionReq.Save]" Method="SessionReq_Save">
    <Parameter Name="DID" Parameter="dID" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(64)" />
    <ElementType Name="SessionReq_SaveResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MemberID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Session.Save]" Method="Session_Save">
    <Parameter Name="SessionReqID" Parameter="sessionReqID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="DID" Parameter="dID" Type="System.String" DbType="VarChar(64)" />
    <ElementType Name="Session_SaveResult">
      <Column Name="SessionID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MemberID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsNewMember" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Member.ReadInstance]" Method="Member_ReadInstance">
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Member_ReadInstanceResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="About" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="IsMale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BirthdayDate" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Member.Save]" Method="Member_Save">
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="Surname" Parameter="surname" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="About" Parameter="about" Type="System.String" DbType="VarChar(1024)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="IsMale" Parameter="isMale" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="BirthdayDate" Parameter="birthdayDate" Type="System.String" DbType="VarChar(32)" />
    <ElementType Name="Member_SaveResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(513)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="About" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="IsMale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="JoinedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BirthdayDate" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ErrorLog_Save" Method="ErrorLog_Save">
    <Parameter Name="Session" Parameter="session" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="FuncName" Parameter="funcName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Params" Parameter="params" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ErrorText" Parameter="errorText" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="ErrorLog_SaveResult">
      <Column Name="" Member="Column1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Community.ReadDict]" Method="Community_ReadDict">
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Community_ReadDictResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Decription" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Tagline" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsMember" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultColumnID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CountMembers" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Community.ReadInstance]" Method="Community_ReadInstance">
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Community_ReadInstanceResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Decription" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Tagline" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsMember" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultColumnID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CountMembers" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Community.ReadMyDict]" Method="Community_ReadMyDict">
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Community_ReadMyDictResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Decription" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Tagline" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsMember" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultColumnID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CountMembers" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Community.ReadSuggestDict]" Method="Community_ReadSuggestDict">
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Community_ReadSuggestDictResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Decription" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Tagline" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsMember" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultColumnID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CountMembers" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Community.Save]" Method="Community_Save">
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="Link" Parameter="link" Type="System.String" DbType="VarChar(1024)" />
    <Parameter Name="Decription" Parameter="decription" Type="System.String" DbType="VarChar(1024)" />
    <Parameter Name="Tagline" Parameter="tagline" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Community_SaveResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Bookmark.Save]" Method="Bookmark_Save">
    <Parameter Name="EntryID" Parameter="entryID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Bookmark_SaveResult">
      <Column Name="IsPin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[News.ReadByMemberID]" Method="News_ReadByMemberID">
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="News_ReadByMemberIDResult">
      <Column Name="Community_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Community_Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Entry_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ColumnCommunity_Name" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ColumnCommunity_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Text" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Entry_CreateDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entry_CreateDateEst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreatorID_Fullname" Type="System.String" DbType="VarChar(513)" CanBeNull="true" />
      <Column Name="IsPin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Bookmark.ReadByMemberID]" Method="Bookmark_ReadByMemberID">
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Bookmark_ReadByMemberIDResult">
      <Column Name="Community_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Community_Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Entry_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ColumnCommunity_Name" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ColumnCommunity_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Text" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Entry_CreateDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entry_CreateDateEst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreatorID_Fullname" Type="System.String" DbType="VarChar(513)" CanBeNull="true" />
      <Column Name="IsPin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[ColumnCommunity.ReadDict]" Method="ColumnCommunity_ReadDict">
    <Parameter Name="CommunityID" Parameter="communityID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="ColumnCommunity_ReadDictResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Entry.ReadByCommunityID]" Method="Entry_ReadByCommunityID">
    <Parameter Name="CommunityID" Parameter="communityID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ColumnID" Parameter="columnID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MemberID" Parameter="memberID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="Entry_ReadByCommunityIDResult">
      <Column Name="Entry_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Community_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Community_Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ColumnCommunity_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ColumnCommunity_Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Entry_Text" Type="System.String" DbType="VarChar(4048)" CanBeNull="true" />
      <Column Name="Entry_CreateDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entry_CreateDateEst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreatorID_Fullname" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="IsPin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>