#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommSta
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hub")]
	public partial class HubDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public HubDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HubConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HubDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HubDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HubDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HubDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GroupAccess_Save")]
		public int GroupAccess_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4028)")] string exception, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4028)")] string innerException)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID, exception, innerException);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Exception_Save")]
		public int Exception_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string methodName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string note, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string exMessage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string exInnerExceptionMessage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string exHelpLink, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> exHResult, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string exSource, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string exStackTrace)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), methodName, note, exMessage, exInnerExceptionMessage, exHelpLink, exHResult, exSource, exStackTrace);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StaCommVKDaily_Save")]
		public int StaCommVKDaily_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dayDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commViews, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commVisitors, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commReach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commReachSubscribers, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commSubscribed, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commUnsubscribed, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commPostCount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> commMembers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID, dayDate, commViews, commVisitors, commReach, commReachSubscribers, commSubscribed, commUnsubscribed, commPostCount, commMembers);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StaCommVKWeekly_Save")]
		public int StaCommVKWeekly_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> weekDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commViews, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commVisitors, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commReach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commReachSubscribers, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commSubscribed, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commUnsubscribed, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> commPostCount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> commMembers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID, weekDate, commViews, commVisitors, commReach, commReachSubscribers, commSubscribed, commUnsubscribed, commPostCount, commMembers);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Comm_ReadForSta")]
		public ISingleResult<Comm_ReadForStaResult> Comm_ReadForSta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsNewComm", DbType="Bit")] System.Nullable<bool> isNewComm, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string areaCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isNewComm, areaCode);
			return ((ISingleResult<Comm_ReadForStaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Times_Save")]
		public int Times_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string sex_graph)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sex_graph);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SexComm_Save")]
		public int SexComm_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> areaCommID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> other, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> under18, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from18to21, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from21to24, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from24to27, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from27to30, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from30to35, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from35to45, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> over45)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID, areaCommID, sex, other, under18, from18to21, from21to24, from24to27, from27to30, from30to35, from35to45, over45);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StaCommVKGraph_Save")]
		public int StaCommVKGraph_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string feedback_graph, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string activity_graph, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string members_graph)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID, feedback_graph, activity_graph, members_graph);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StaCommOKTopics_Save")]
		public int StaCommOKTopics_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dayDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string statTopics)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID, dayDate, statTopics);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StaCommOKTrends_Save")]
		public int StaCommOKTrends_Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dayDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string statTrends)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID, dayDate, statTrends);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Comm_Set")]
		public int Comm_Set([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(512)")] string link, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(256)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(512)")] string photoLink, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(512)")] string photoLinkBig, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(32)")] string areaCommCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> members_count, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(512)")] string screenName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), link, groupID, name, photoLink, photoLinkBig, areaCommCode, members_count, screenName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Comm_ReadForStaVKGraph")]
		public ISingleResult<Comm_ReadForStaVKGraphResult> Comm_ReadForStaVKGraph([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> topCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), topCount);
			return ((ISingleResult<Comm_ReadForStaVKGraphResult>)(result.ReturnValue));
		}
	}
	
	public partial class Comm_ReadForStaResult
	{
		
		private System.Nullable<long> _groupID;
		
		private string _link;
		
		public Comm_ReadForStaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupID", DbType="BigInt")]
		public System.Nullable<long> groupID
		{
			get
			{
				return this._groupID;
			}
			set
			{
				if ((this._groupID != value))
				{
					this._groupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(512)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this._link = value;
				}
			}
		}
	}
	
	public partial class Comm_ReadForStaVKGraphResult
	{
		
		private System.Nullable<long> _groupID;
		
		private string _link;
		
		private System.Nullable<System.DateTime> _requestDate;
		
		public Comm_ReadForStaVKGraphResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupID", DbType="BigInt")]
		public System.Nullable<long> groupID
		{
			get
			{
				return this._groupID;
			}
			set
			{
				if ((this._groupID != value))
				{
					this._groupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(512)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this._link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> requestDate
		{
			get
			{
				return this._requestDate;
			}
			set
			{
				if ((this._requestDate != value))
				{
					this._requestDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
