<?xml version="1.0" encoding="utf-8"?><Database Name="Hub" Class="HubDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=95.84.164.113;Initial Catalog=Hub;User ID=hubber" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HubConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GroupAccess_Save" Method="GroupAccess_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="exception" Type="System.String" DbType="VarChar(4028)" />
    <Parameter Name="innerException" Type="System.String" DbType="VarChar(4028)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Exception_Save" Method="Exception_Save">
    <Parameter Name="methodName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="note" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exMessage" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exInnerExceptionMessage" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exHelpLink" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exHResult" Type="System.Int32" DbType="Int" />
    <Parameter Name="exSource" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exStackTrace" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StaCommVKDaily_Save" Method="StaCommVKDaily_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="dayDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="commViews" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commVisitors" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReach" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReachSubscribers" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commSubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commUnsubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commPostCount" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commMembers" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StaCommVKWeekly_Save" Method="StaCommVKWeekly_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="weekDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="commViews" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commVisitors" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReach" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReachSubscribers" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commSubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commUnsubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commPostCount" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commMembers" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comm_ReadForSta" Method="Comm_ReadForSta">
    <Parameter Name="IsNewComm" Parameter="isNewComm" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="areaCode" Type="System.String" DbType="VarChar(2)" />
    <ElementType Name="Comm_ReadForStaResult">
      <Column Name="groupID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Times_Save" Method="Times_Save">
    <Parameter Name="sex_graph" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SexComm_Save" Method="SexComm_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="areaCommID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sex" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="other" Type="System.Int32" DbType="Int" />
    <Parameter Name="under18" Type="System.Int32" DbType="Int" />
    <Parameter Name="from18to21" Type="System.Int32" DbType="Int" />
    <Parameter Name="from21to24" Type="System.Int32" DbType="Int" />
    <Parameter Name="from24to27" Type="System.Int32" DbType="Int" />
    <Parameter Name="from27to30" Type="System.Int32" DbType="Int" />
    <Parameter Name="from30to35" Type="System.Int32" DbType="Int" />
    <Parameter Name="from35to45" Type="System.Int32" DbType="Int" />
    <Parameter Name="over45" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StaCommVKGraph_Save" Method="StaCommVKGraph_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="feedback_graph" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="activity_graph" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="members_graph" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StaCommOKTopics_Save" Method="StaCommOKTopics_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="dayDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="statTopics" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StaCommOKTrends_Save" Method="StaCommOKTrends_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="dayDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="statTrends" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comm_Set" Method="Comm_Set">
    <Parameter Name="link" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="photoLink" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="photoLinkBig" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="areaCommCode" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="members_count" Type="System.Int32" DbType="Int" />
    <Parameter Name="screenName" Type="System.String" DbType="VarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comm_ReadForStaVKGraph" Method="Comm_ReadForStaVKGraph">
    <Parameter Name="topCount" Type="System.Int32" DbType="Int" />
    <ElementType Name="Comm_ReadForStaVKGraphResult">
      <Column Name="groupID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="requestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>