<?xml version="1.0" encoding="utf-8"?><Database Name="Hub" Class="HubDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=95.84.164.113;Initial Catalog=Hub;User ID=hubber" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HubConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GroupAccess_Save" Method="GroupAccess_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="exception" Type="System.String" DbType="VarChar(4028)" />
    <Parameter Name="innerException" Type="System.String" DbType="VarChar(4028)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Exception_Save" Method="Exception_Save">
    <Parameter Name="methodName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="note" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exMessage" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exInnerExceptionMessage" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exHelpLink" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exHResult" Type="System.Int32" DbType="Int" />
    <Parameter Name="exSource" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="exStackTrace" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comm_ReadForSta" Method="Comm_ReadForSta">
    <Parameter Name="IsNewComm" Parameter="isNewComm" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="Comm_ReadForStaResult">
      <Column Name="groupID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Comm_Set" Method="Comm_Set">
    <Parameter Name="link" Type="System.String" DbType="VarChar(512)" />
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="photoLink" Type="System.String" DbType="VarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StaCommVKDaily_Save" Method="StaCommVKDaily_Save">
    <Parameter Name="groupID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="dayDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="commViews" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commVisitors" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReach" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReachSubscribers" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commSubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commUnsubscribed" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commLikes" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commComments" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commReposts" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commPostCount" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="commMembers" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>